### ISSUE TITLE
Syntax Error when opening servers in WHMCS

### ISSUE THREAD

**Issue by tmunsch** [easypanel-io/whmcs-plugin#10]
WHMCS Version 8.10.1

I receive the below error when opening "Servers" under system settings

``ParseError: syntax error, unexpected 'throw' (T_THROW) in /home/domain.com/public_html/modules/servers/easypanel/easypanel.php:162
Stack trace:
#0 /home/domain.com/public_html/admin/configservers.php(0): WHMCS\Module\AbstractModule->load()
#1 {main}``

**Comment by mateuslacorte** [comment]
Looking at it

**Comment by mateuslacorte** [comment]
Fixed on version v1.0.2.
