### ISSUE TITLE
No UAC communication between the panel and whmcs. 

### ISSUE THREAD

**Issue by NovaPlayzGames** [easypanel-io/whmcs-plugin#20]
it seems to not create a user account and link it to the service purchased, it is not that big of a deal as for some of the plans i sell there will still need to be manual work but i would like to have a user account created with the email from the users account on purchase to ease a little workload.

**Comment by deiucanta** [comment]
@mateuslacorte what do you think?

**Comment by mateuslacorte** [comment]
Can’t happen, the easy panel doesn’t have restrictions for a user, so if the user got an account on easy panel it would mean the user will be able to create how many projects and services he wants on easy panel without paying
